name: composer
title: Composer
version: [2.10.3]
category: application
description: Composer is a dependency manager for PHP. It allows you to declare the libraries your project depends on and it will manage (install/update) them for you.
tags: [php, composer]
scripts:
  install: install.sh
  uninstall: uninstall.sh
options:
  install:
    - name: INSTALL_SOURCE
      label: Download Source
      type: select
      default: official
      desc: default is official source, you can choose the mirror source to speed up the download.
      choices:
        - label: getcomposer.org (default)
          value: official
        - label: pkg.xyz (China mirror)
          value: mirror
    - name: ENABLE_MIRROR
      label: Enable Global Proxy (Packagist China Mirror)   
      type: bool
      default: false
      desc: By checking this option, you will switch Composer's dependency repository (Packagist) to the pkg.xyz China full mirror and write it to the global configuration file (~/.config/composer/config.json) — this is the official recommendation for "modifying the global configuration file", affecting all projects for the current system user, significantly speeding up domestic dependency fetching; if not checked, the official source will be maintained. When uninstalling, if it still points to this mirror, it will be automatically reverted.
