name: php
title: PHP
version: [8.3.3,7.4.33]
category: application
description: PHP is a server-side scripting language designed for web development.
icon: php.png
tags: [php]
allow_multiple_instances: 'yes'
actions:
  build: 编译安装
scripts:
  install: install.sh
  uninstall: uninstall.sh
options:
  build:
    - name: EXTS
      type: multiselect
      title: 扩展
      desc: 选择需要安装的扩展
      choices:
        - label: bcmath
          value: bcmath
        - label: calendar
          value: calendar
        - label: exif
          value: exif
        - label: fileinfo
          value: fileinfo
      