name: mysql
title: MySQL Community Server
version: [9.7.2,8.4.11,8.0.46]
category: database
description: MySQL is a relational database management system (RDBMS) developed by Oracle. 
icon: mysql.png
tags: [mysql,db]
allow_multiple_instances: 'no'
actions:
  bin: Install
scripts:
  install: install.sh
options:
  bin:
    - name: SET_DEFAULT
      label: Symbolic Link
      type: bool
      default: false
      desc: If checked, the symbolic link will be created in /usr/local/bin (mysql / mysqladmin / mysqldump / mysqlcheck)
