name: mariadb
title: MariaDB Server
version: [12.3.3,11.8.9,10.11.19]
category: database
description: MariaDB is a community-developed fork of MySQL. The open source relational database.
icon: mariadb.png
tags: [mariadb,db,mysql]
allow_multiple_instances: 'no'

